---
stages:
  build:
    buildTool: "mta"
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N24"
    npmLint:
      failOnError: false
  malwareScan:
    scan: false
    _additional: {}
  additionalTests:
    runFirst:
      command: "sh .sap_cid/quality-gate.sh"
